menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open

highlight_theme: mac #  darker / pale night / light / ocean / mac / mac light / false

inject:
  bottom:
    - <script src="https://unpkg.com/axios"></script>

CDN:
  third_party_provider: custom
  custom_format: https://unpkg.com/${name}@${version}/${file}

  option:
    twikoo: https://unpkg.com/twikoo
