menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open

highlight_theme: mac #  darker / pale night / light / ocean / mac / mac light / false

inject:
  head:
    # 自定义css
    - <link rel="stylesheet" href="/css/custom.css">
  bottom:
    - <script src="https://registry.npmmirror.com/axios/latest/files/dist/axios.min.js"></script>

CDN:
  third_party_provider: custom
  custom_format: https://registry.npmmirror.com/${name}/${version}/files/${file}

  option:
    twikoo: https://registry.npmmirror.com/twikoo/1.6.31/files/dist/twikoo.all.min.js
